In [47]:
import pandas as pd
import numpy as np
import json

In [2]:
data = pd.read_json('./springfield.json')
data

,id,region,type,units,history,fuel_tech,forecast
0,Springfield.fuel_tech.black_coal.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",black_coal,NaN
1,Springfield.fuel_tech.distillate.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",distillate,NaN
2,Springfield.fuel_tech.gas_ccgt.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",gas_ccgt,NaN
3,Springfield.fuel_tech.hydro.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",hydro,NaN
4,Springfield.fuel_tech.pumps.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",pumps,NaN
5,Springfield.fuel_tech.wind.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",wind,NaN
6,Springfield.fuel_tech.exports.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",exports,NaN
7,Springfield.fuel_tech.rooftop_solar.power,Springfield,power,MW,"{'start': 1571578200, 'last': 1571580000, 'int...",rooftop_solar,"{'start': '2019-10-21T00:00+1000', 'last': '20..."
8,Springfield.price,Springfield,price,USD/MWh,"{'start': 1571578200, 'last': 1572183000, 'int...",NaN,NaN
9,Springfield.demand,Springfield,demand,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",NaN,NaN
10,Springfield.temperature,Springfield,temperature,degreesF,"{'start': 1571578200, 'last': 1572183000, 'int...",NaN,NaN

In [39]:
# get temperature
temperature = data.iloc[-1, :]['history']
temperature

{'start': 1571578200,
 'last': 1572183000,
 'interval': '30m',
 'data': [58,
  57,
  57,
  56,
  56,
  55,
  55,
  55,
  54,
  54,
  54,
  54,
  55,
  56,
  59,
  60,
  61,
  65,
  67,
  69,
  70,
  72,
  72,
  71,
  71,
  72,
  72,
  69,
  71,
  69,
  70,
  69,
  69,
  68,
  68,
  67,
  66,
  66,
  65,
  65,
  65,
  65,
  64,
  64,
  64,
  63,
  62,
  60,
  60,
  59,
  58,
  58,
  58,
  57,
  57,
  57,
  56,
  56,
  56,
  56,
  57,
  59,
  60,
  61,
  64,
  67,
  69,
  72,
  73,
  73,
  74,
  73,
  73,
  74,
  72,
  72,
  73,
  70,
  71,
  70,
  70,
  69,
  68,
  68,
  67,
  67,
  67,
  67,
  67,
  66,
  66,
  66,
  66,
  66,
  66,
  65,
  65,
  65,
  65,
  65,
  65,
  64,
  62,
  62,
  61,
  61,
  61,
  60,
  61,
  62,
  64,
  68,
  70,
  69,
  74,
  74,
  74,
  74,
  75,
  75,
  74,
  74,
  74,
  73,
  73,
  74,
  73,
  73,
  73,
  73,
  71,
  70,
  69,
  69,
  69,
  69,
  69,
  68,
  68,
  67,
  69,
  68,
  67,
  67,
  66,
  66,
  66,
  66,
  66,
  66,
  66,
  65,
  65,
  65,
  65,
  65,
  66,
  67,
  69,
  70,
  72,
  74,
  74,
  78,
  76,
  78,
  77,
  78,
  77,
  76,
  75,
  75,
  76,
  78,
  74,
  72,
  74,
  73,
  72,
  73,
  73,
  73,
  72,
  70,
  69,
  69,
  68,
  68,
  68,
  68,
  67,
  67,
  67,
  66,
  66,
  65,
  65,
  65,
  64,
  65,
  64,
  64,
  67,
  67,
  69,
  73,
  76,
  78,
  82,
  84,
  86,
  87,
  89,
  91,
  92,
  93,
  95,
  96,
  95,
  97,
  97,
  91,
  83,
  82,
  79,
  78,
  78,
  83,
  82,
  80,
  77,
  80,
  80,
  79,
  78,
  77,
  78,
  78,
  78,
  80,
  79,
  81,
  80,
  80,
  79,
  80,
  78,
  78,
  74,
  74,
  74,
  74,
  74,
  74,
  77,
  77,
  81,
  81,
  80,
  84,
  85,
  85,
  85,
  87,
  88,
  88,
  86,
  87,
  88,
  87,
  86,
  84,
  82,
  80,
  79,
  77,
  75,
  74,
  73,
  73,
  72,
  71,
  70,
  69,
  68,
  68,
  67,
  67,
  67,
  66,
  65,
  65,
  64,
  63,
  63,
  62,
  62,
  61,
  61,
  61,
  62,
  63,
  64,
  65,
  67,
  68,
  69,
  71,
  72,
  71,
  70,
  70,
  70,
  71,
  69,
  70,
  70,
  69,
  69,
  69,
  68,
  67,
  66,
  66,
  66,
  65,
  65,
  66,
  65,
  65,
  65,
  64,
  63,
  62,
  62,
  61]}

In [53]:
start = temperature['start']
interval = 1800
time_temp = list()
for i in range(len(temperature['data'])):
    time_temp.append([start+interval, temperature['data'][i]])
    start += interval
time_temp

[[1571580000, 58],
 [1571581800, 57],
 [1571583600, 57],
 [1571585400, 56],
 [1571587200, 56],
 [1571589000, 55],
 [1571590800, 55],
 [1571592600, 55],
 [1571594400, 54],
 [1571596200, 54],
 [1571598000, 54],
 [1571599800, 54],
 [1571601600, 55],
 [1571603400, 56],
 [1571605200, 59],
 [1571607000, 60],
 [1571608800, 61],
 [1571610600, 65],
 [1571612400, 67],
 [1571614200, 69],
 [1571616000, 70],
 [1571617800, 72],
 [1571619600, 72],
 [1571621400, 71],
 [1571623200, 71],
 [1571625000, 72],
 [1571626800, 72],
 [1571628600, 69],
 [1571630400, 71],
 [1571632200, 69],
 [1571634000, 70],
 [1571635800, 69],
 [1571637600, 69],
 [1571639400, 68],
 [1571641200, 68],
 [1571643000, 67],
 [1571644800, 66],
 [1571646600, 66],
 [1571648400, 65],
 [1571650200, 65],
 [1571652000, 65],
 [1571653800, 65],
 [1571655600, 64],
 [1571657400, 64],
 [1571659200, 64],
 [1571661000, 63],
 [1571662800, 62],
 [1571664600, 60],
 [1571666400, 60],
 [1571668200, 59],
 [1571670000, 58],
 [1571671800, 58],
 [1571673600, 58],
 [1571675400, 57],
 [1571677200, 57],
 [1571679000, 57],
 [1571680800, 56],
 [1571682600, 56],
 [1571684400, 56],
 [1571686200, 56],
 [1571688000, 57],
 [1571689800, 59],
 [1571691600, 60],
 [1571693400, 61],
 [1571695200, 64],
 [1571697000, 67],
 [1571698800, 69],
 [1571700600, 72],
 [1571702400, 73],
 [1571704200, 73],
 [1571706000, 74],
 [1571707800, 73],
 [1571709600, 73],
 [1571711400, 74],
 [1571713200, 72],
 [1571715000, 72],
 [1571716800, 73],
 [1571718600, 70],
 [1571720400, 71],
 [1571722200, 70],
 [1571724000, 70],
 [1571725800, 69],
 [1571727600, 68],
 [1571729400, 68],
 [1571731200, 67],
 [1571733000, 67],
 [1571734800, 67],
 [1571736600, 67],
 [1571738400, 67],
 [1571740200, 66],
 [1571742000, 66],
 [1571743800, 66],
 [1571745600, 66],
 [1571747400, 66],
 [1571749200, 66],
 [1571751000, 65],
 [1571752800, 65],
 [1571754600, 65],
 [1571756400, 65],
 [1571758200, 65],
 [1571760000, 65],
 [1571761800, 64],
 [1571763600, 62],
 [1571765400, 62],
 [1571767200, 61],
 [1571769000, 61],
 [1571770800, 61],
 [1571772600, 60],
 [1571774400, 61],
 [1571776200, 62],
 [1571778000, 64],
 [1571779800, 68],
 [1571781600, 70],
 [1571783400, 69],
 [1571785200, 74],
 [1571787000, 74],
 [1571788800, 74],
 [1571790600, 74],
 [1571792400, 75],
 [1571794200, 75],
 [1571796000, 74],
 [1571797800, 74],
 [1571799600, 74],
 [1571801400, 73],
 [1571803200, 73],
 [1571805000, 74],
 [1571806800, 73],
 [1571808600, 73],
 [1571810400, 73],
 [1571812200, 73],
 [1571814000, 71],
 [1571815800, 70],
 [1571817600, 69],
 [1571819400, 69],
 [1571821200, 69],
 [1571823000, 69],
 [1571824800, 69],
 [1571826600, 68],
 [1571828400, 68],
 [1571830200, 67],
 [1571832000, 69],
 [1571833800, 68],
 [1571835600, 67],
 [1571837400, 67],
 [1571839200, 66],
 [1571841000, 66],
 [1571842800, 66],
 [1571844600, 66],
 [1571846400, 66],
 [1571848200, 66],
 [1571850000, 66],
 [1571851800, 65],
 [1571853600, 65],
 [1571855400, 65],
 [1571857200, 65],
 [1571859000, 65],
 [1571860800, 66],
 [1571862600, 67],
 [1571864400, 69],
 [1571866200, 70],
 [1571868000, 72],
 [1571869800, 74],
 [1571871600, 74],
 [1571873400, 78],
 [1571875200, 76],
 [1571877000, 78],
 [1571878800, 77],
 [1571880600, 78],
 [1571882400, 77],
 [1571884200, 76],
 [1571886000, 75],
 [1571887800, 75],
 [1571889600, 76],
 [1571891400, 78],
 [1571893200, 74],
 [1571895000, 72],
 [1571896800, 74],
 [1571898600, 73],
 [1571900400, 72],
 [1571902200, 73],
 [1571904000, 73],
 [1571905800, 73],
 [1571907600, 72],
 [1571909400, 70],
 [1571911200, 69],
 [1571913000, 69],
 [1571914800, 68],
 [1571916600, 68],
 [1571918400, 68],
 [1571920200, 68],
 [1571922000, 67],
 [1571923800, 67],
 [1571925600, 67],
 [1571927400, 66],
 [1571929200, 66],
 [1571931000, 65],
 [1571932800, 65],
 [1571934600, 65],
 [1571936400, 64],
 [1571938200, 65],
 [1571940000, 64],
 [1571941800, 64],
 [1571943600, 67],
 [1571945400, 67],
 [1571947200, 69],
 [1571949000, 73],
 [1571950800, 76],
 [1571952600, 78],
 [1571954400, 82],
 [1571956200, 84],
 [1571958000, 86],
 [1571959800, 87],
 [1571961600, 89],
 [1571963400, 91],
 [1571965200, 92],
 [1571967000, 93],
 [1571968800, 95],
 [1571970600, 96],
 [1571972400, 95],
 [1571974200, 97],
 [1571976000, 97],
 [1571977800, 91],
 [1571979600, 83],
 [1571981400, 82],
 [1571983200, 79],
 [1571985000, 78],
 [1571986800, 78],
 [1571988600, 83],
 [1571990400, 82],
 [1571992200, 80],
 [1571994000, 77],
 [1571995800, 80],
 [1571997600, 80],
 [1571999400, 79],
 [1572001200, 78],
 [1572003000, 77],
 [1572004800, 78],
 [1572006600, 78],
 [1572008400, 78],
 [1572010200, 80],
 [1572012000, 79],
 [1572013800, 81],
 [1572015600, 80],
 [1572017400, 80],
 [1572019200, 79],
 [1572021000, 80],
 [1572022800, 78],
 [1572024600, 78],
 [1572026400, 74],
 [1572028200, 74],
 [1572030000, 74],
 [1572031800, 74],
 [1572033600, 74],
 [1572035400, 74],
 [1572037200, 77],
 [1572039000, 77],
 [1572040800, 81],
 [1572042600, 81],
 [1572044400, 80],
 [1572046200, 84],
 [1572048000, 85],
 [1572049800, 85],
 [1572051600, 85],
 [1572053400, 87],
 [1572055200, 88],
 [1572057000, 88],
 [1572058800, 86],
 [1572060600, 87],
 [1572062400, 88],
 [1572064200, 87],
 [1572066000, 86],
 [1572067800, 84],
 [1572069600, 82],
 [1572071400, 80],
 [1572073200, 79],
 [1572075000, 77],
 [1572076800, 75],
 [1572078600, 74],
 [1572080400, 73],
 [1572082200, 73],
 [1572084000, 72],
 [1572085800, 71],
 [1572087600, 70],
 [1572089400, 69],
 [1572091200, 68],
 [1572093000, 68],
 [1572094800, 67],
 [1572096600, 67],
 [1572098400, 67],
 [1572100200, 66],
 [1572102000, 65],
 [1572103800, 65],
 [1572105600, 64],
 [1572107400, 63],
 [1572109200, 63],
 [1572111000, 62],
 [1572112800, 62],
 [1572114600, 61],
 [1572116400, 61],
 [1572118200, 61],
 [1572120000, 62],
 [1572121800, 63],
 [1572123600, 64],
 [1572125400, 65],
 [1572127200, 67],
 [1572129000, 68],
 [1572130800, 69],
 [1572132600, 71],
 [1572134400, 72],
 [1572136200, 71],
 [1572138000, 70],
 [1572139800, 70],
 [1572141600, 70],
 [1572143400, 71],
 [1572145200, 69],
 [1572147000, 70],
 [1572148800, 70],
 [1572150600, 69],
 [1572152400, 69],
 [1572154200, 69],
 [1572156000, 68],
 [1572157800, 67],
 [1572159600, 66],
 [1572161400, 66],
 [1572163200, 66],
 [1572165000, 65],
 [1572166800, 65],
 [1572168600, 66],
 [1572170400, 65],
 [1572172200, 65],
 [1572174000, 65],
 [1572175800, 64],
 [1572177600, 63],
 [1572179400, 62],
 [1572181200, 62],
 [1572183000, 61]]

In [55]:
with open('time_temp.json', 'w') as outfile:
    json.dump(time_temp, outfile)

In [56]:
data.iloc[1, 4]

,id,region,type,units,history,fuel_tech,forecast
0,Springfield.fuel_tech.black_coal.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",black_coal,NaN
1,Springfield.fuel_tech.distillate.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",distillate,NaN
2,Springfield.fuel_tech.gas_ccgt.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",gas_ccgt,NaN
3,Springfield.fuel_tech.hydro.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",hydro,NaN
4,Springfield.fuel_tech.pumps.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",pumps,NaN
5,Springfield.fuel_tech.wind.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",wind,NaN
6,Springfield.fuel_tech.exports.power,Springfield,power,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",exports,NaN
7,Springfield.fuel_tech.rooftop_solar.power,Springfield,power,MW,"{'start': 1571578200, 'last': 1571580000, 'int...",rooftop_solar,"{'start': '2019-10-21T00:00+1000', 'last': '20..."
8,Springfield.price,Springfield,price,USD/MWh,"{'start': 1571578200, 'last': 1572183000, 'int...",NaN,NaN
9,Springfield.demand,Springfield,demand,MW,"{'start': 1571579700, 'last': 1572184500, 'int...",NaN,NaN
10,Springfield.temperature,Springfield,temperature,degreesF,"{'start': 1571578200, 'last': 1572183000, 'int...",NaN,NaN